# Generated by Django 4.1.7 on 2023-04-24 02:30

from django.db import migrations, models
import django.db.models.deletion
import phonenumber_field.modelfields


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Customer",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "type",
                    models.CharField(
                        choices=[
                            ("RE", "Retail"),
                            ("WH", "Wholesale"),
                            ("PA", "Partner"),
                        ],
                        default="RE",
                        max_length=100,
                    ),
                ),
                ("full_name", models.CharField(max_length=100)),
                ("city", models.CharField(max_length=100)),
                (
                    "phone_number",
                    phonenumber_field.modelfields.PhoneNumberField(
                        blank=True, max_length=128, region=None
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Item",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("model", models.CharField(max_length=100)),
                ("brand", models.CharField(max_length=100)),
                ("quantity", models.IntegerField(default=0)),
                ("description", models.CharField(max_length=250)),
                ("active", models.BooleanField()),
                ("type", models.CharField(max_length=100)),
                ("category", models.CharField(max_length=100)),
                ("order_date", models.DateTimeField(verbose_name="date ordered")),
                ("check_date", models.DateTimeField(verbose_name="date checked")),
            ],
        ),
        migrations.CreateModel(
            name="ItemStatus",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("item_status", models.CharField(blank=True, max_length=100)),
                ("description", models.CharField(max_length=250, null=True)),
            ],
            options={
                "verbose_name_plural": "Item status",
            },
        ),
        migrations.CreateModel(
            name="Region",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=200)),
                ("description", models.CharField(max_length=250)),
                ("address", models.CharField(max_length=200)),
                ("city", models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name="Location",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=200)),
                ("description", models.CharField(max_length=250)),
                (
                    "region",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        to="inventory.region",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="ItemEvent",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "type",
                    models.CharField(
                        choices=[
                            ("CH", "Check in"),
                            ("ST", "Stored in warehouse"),
                            ("BO", "Borrowed"),
                            ("RE", "Returned"),
                            ("DA", "Damaged"),
                            ("RP", "Out for repair"),
                            ("LO", "Lost"),
                            ("SO", "Sold"),
                        ],
                        default="CH",
                        max_length=100,
                    ),
                ),
                ("timestamp", models.DateTimeField(verbose_name="date and time event")),
                ("status", models.CharField(max_length=100)),
                (
                    "customer",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        to="inventory.customer",
                    ),
                ),
                (
                    "item",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="inventory.item"
                    ),
                ),
                (
                    "location",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        to="inventory.location",
                    ),
                ),
            ],
        ),
        migrations.AddField(
            model_name="item",
            name="item_status",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                to="inventory.itemstatus",
            ),
        ),
        migrations.AddField(
            model_name="item",
            name="location",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to="inventory.location",
            ),
        ),
    ]
