# Generated by Django 4.1.7 on 2023-04-09 22:11

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("inventory", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="item",
            name="check_date",
            field=models.DateTimeField(verbose_name="date published"),
        ),
    ]
