# Generated by Django 4.1.7 on 2023-04-10 00:54

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("inventory", "0002_alter_item_check_date"),
    ]

    operations = [
        migrations.AlterField(
            model_name="item",
            name="brand",
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name="item",
            name="category",
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name="item",
            name="description",
            field=models.CharField(max_length=250),
        ),
        migrations.AlterField(
            model_name="item",
            name="model",
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name="item",
            name="status",
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name="item",
            name="type",
            field=models.CharField(max_length=100),
        ),
    ]
