# Generated by Django 4.1.7 on 2023-04-10 00:59

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("inventory", "0003_alter_item_brand_alter_item_category_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="item",
            name="check_date",
            field=models.DateField(verbose_name="date published"),
        ),
        migrations.AlterField(
            model_name="item",
            name="order_date",
            field=models.DateField(verbose_name="date ordered"),
        ),
        migrations.CreateModel(
            name="Item_event",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("timestamp", models.DateTimeField(verbose_name="date and time event")),
                ("type", models.CharField(max_length=100)),
                ("status", models.CharField(max_length=100)),
                (
                    "item_id",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="inventory.item"
                    ),
                ),
            ],
        ),
    ]
