# Generated by Django 4.1.7 on 2023-04-10 02:50

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("inventory", "0004_alter_item_check_date_alter_item_order_date_and_more"),
    ]

    operations = [
        migrations.RenameModel(
            old_name="Item_event",
            new_name="ItemEvent",
        ),
        migrations.AlterField(
            model_name="item",
            name="check_date",
            field=models.DateTimeField(verbose_name="date checked"),
        ),
        migrations.AlterField(
            model_name="item",
            name="order_date",
            field=models.DateTimeField(verbose_name="date ordered"),
        ),
    ]
