# Generated by Django 4.1.7 on 2023-04-12 01:46

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("inventory", "0006_customer_itemevent_customer_id"),
    ]

    operations = [
        migrations.AlterField(
            model_name="itemevent",
            name="customer_id",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                to="inventory.customer",
            ),
        ),
    ]
