# Generated by Django 4.1.7 on 2023-04-14 00:39

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("inventory", "0008_location_item_location_id_itemevent_location_id"),
    ]

    operations = [
        migrations.CreateModel(
            name="Region",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=200)),
                ("description", models.CharField(max_length=250)),
                ("address", models.CharField(max_length=200)),
                ("city", models.CharField(max_length=100)),
            ],
        ),
        migrations.AddField(
            model_name="location",
            name="region_id",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                to="inventory.customer",
            ),
        ),
    ]
