# Generated by Django 4.1.7 on 2023-04-14 00:42

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("inventory", "0009_region_location_region_id"),
    ]

    operations = [
        migrations.AlterField(
            model_name="location",
            name="region_id",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                to="inventory.region",
            ),
        ),
    ]
