# Generated by Django 4.1.7 on 2023-04-18 03:51

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("inventory", "0010_alter_location_region_id"),
    ]

    operations = [
        migrations.CreateModel(
            name="ItemStatus",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("item_status", models.CharField(blank=True, max_length=100)),
            ],
        ),
        migrations.RemoveField(
            model_name="item",
            name="status",
        ),
        migrations.AddField(
            model_name="item",
            name="item_status",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                to="inventory.itemstatus",
            ),
        ),
    ]
