# Generated by Django 4.1.7 on 2023-04-18 05:01

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("inventory", "0011_itemstatus_remove_item_status_item_item_status"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="itemstatus",
            options={"verbose_name_plural": "Item status"},
        ),
    ]
