# Generated by Django 4.1.7 on 2023-04-19 01:05

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("inventory", "0012_alter_itemstatus_options"),
    ]

    operations = [
        migrations.AddField(
            model_name="itemstatus",
            name="description",
            field=models.CharField(max_length=250, null=True),
        ),
    ]
