# Generated by Django 4.1.7 on 2023-04-20 00:24

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("inventory", "0013_itemstatus_description"),
    ]

    operations = [
        migrations.AlterField(
            model_name="location",
            name="type",
            field=models.CharField(
                choices=[("PH", "Physical"), ("PA", "Partner"), ("VI", "Virtual")],
                default="PH",
                max_length=100,
            ),
        ),
    ]
