# Generated by Django 4.1.7 on 2023-04-20 23:49

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("inventory", "0014_alter_location_type"),
    ]

    operations = [
        migrations.AlterField(
            model_name="customer",
            name="type",
            field=models.CharField(
                choices=[("RE", "Retail"), ("WH", "Wholesale")],
                default="WH",
                max_length=100,
            ),
        ),
    ]
