# Generated by Django 4.1.7 on 2023-04-23 22:58

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("inventory", "0015_alter_customer_type"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="location",
            name="type",
        ),
        migrations.AlterField(
            model_name="customer",
            name="type",
            field=models.CharField(
                choices=[("RE", "Retail"), ("WH", "Wholesale"), ("PA", "Partner")],
                default="WH",
                max_length=100,
            ),
        ),
    ]
