# Generated by Django 4.1.7 on 2023-04-23 23:24

from django.db import migrations, models
import phonenumber_field.modelfields


class Migration(migrations.Migration):
    dependencies = [
        ("inventory", "0016_remove_location_type_alter_customer_type"),
    ]

    operations = [
        migrations.AddField(
            model_name="customer",
            name="phone_number",
            field=phonenumber_field.modelfields.PhoneNumberField(
                blank=True, max_length=128, region=None
            ),
        ),
        migrations.AlterField(
            model_name="customer",
            name="type",
            field=models.CharField(
                choices=[("RE", "Retail"), ("WH", "Wholesale"), ("PA", "Partner")],
                default="RE",
                max_length=100,
            ),
        ),
    ]
