# Generated by Django 4.1.7 on 2023-04-23 23:43

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("inventory", "0017_customer_phone_number_alter_customer_type"),
    ]

    operations = [
        migrations.AddField(
            model_name="location",
            name="type",
            field=models.CharField(
                choices=[("UN", "Unitaria"), ("GR", "Grupal")],
                default="UN",
                max_length=100,
            ),
        ),
    ]
