# Generated by Django 4.1.7 on 2023-04-24 00:09

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("inventory", "0018_location_type"),
    ]

    operations = [
        migrations.AlterField(
            model_name="itemevent",
            name="type",
            field=models.CharField(
                choices=[
                    ("CH", "Check in"),
                    ("ST", "Store in warehouse"),
                    ("BO", "Borrowed"),
                    ("RE", "Returned"),
                    ("DA", "Damaged"),
                    ("RP", "Out for repair"),
                    ("LO", "Lost"),
                    ("SO", "Sold"),
                ],
                default="CH",
                max_length=100,
            ),
        ),
    ]
