# Generated by Django 4.1.7 on 2023-04-24 01:10

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("inventory", "0019_alter_itemevent_type"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="location",
            name="type",
        ),
        migrations.AlterField(
            model_name="itemevent",
            name="type",
            field=models.CharField(
                choices=[
                    ("CH", "Check in"),
                    ("ST", "Stored in warehouse"),
                    ("BO", "Borrowed"),
                    ("RE", "Returned"),
                    ("DA", "Damaged"),
                    ("RP", "Out for repair"),
                    ("LO", "Lost"),
                    ("SO", "Sold"),
                ],
                default="CH",
                max_length=100,
            ),
        ),
    ]
